/**
 * Enum for user input types.
 */
export enum UserInputType {
    Left = "ArrowLeft",
    Right = "ArrowRight",
    Shoot = " ",
    Up = "ArrowUp",
    Down = "ArrowDown",
    Enter = "Enter",
    ToggleHUD = "ToggleHUD",
    Escape = "Escape",
    Shift = "Shift",
    Num1 = "1",
    Num2 = "2",
    Num3 = "3",
    Num4 = "4",
    Num5 = "5",
    Num6 = "6",
    Num7 = "7",
    Num8 = "8",
    Num9 = "9",
    Num0 = "0",
    Exclamation = "!",
    AtSign = "@",
    Hash = "#",
    Dollar = "$",
    Percent = "%",
    Caret = "^",
    Asterisk = "*",
    Ampersand = "&",
    EAcute = "é",
    DoubleQuote = "\"",
    SingleQuote = "'",
    LeftParenthesis = "(",
    Dash = "-",
    EGrave = "è",
    Underscore = "_",
    CCedilla = "ç",
    AGrave = "à",
    RightParenthesis = ")",
    Equals = "=",
}