import { GameBonusType } from "../bonus/GameBonusTypes";
import { ProjectileType } from "../projectile/ProjectileType";
import { IInvaderCharacteristics } from "./IInvaderCharacteristics";
import { InvaderType } from "./InvaderType";

export const InvaderSpecs: Record<InvaderType, IInvaderCharacteristics> = {
    [InvaderType.None]: {
        type: InvaderType.None,
        width: 0,
        height: 0,
        moveSpeed: 0,
        score: 0,
        hp: 0,
        shield: 0,
        damage: 0,
        regenerationRate: 0,
        projectileType: ProjectileType.None,
        fireRate: 0,
        shootProbability: 0,
        emitProbability: 0,
        bonusTypes: [],
    },
    [InvaderType.Light]: {
        type: InvaderType.Light,
        width: 30,
        height: 30,
        moveSpeed: 150,
        score: 10,
        hp: 1,
        shield: 0,
        damage: 1,
        regenerationRate: 0,
        projectileType: ProjectileType.None,
        fireRate: 1,
        shootProbability: 0,
        emitProbability: 0.08,
        bonusTypes: [GameBonusType.Speed_Increase_5_Speed_60sec],
    },
    [InvaderType.Basic]: {
        type: InvaderType.Basic,
        width: 40,
        height: 40,
        moveSpeed: 80,
        score: 20,
        hp: 2,
        shield: 0,
        damage: 1,
        regenerationRate: 0.1,
        projectileType: ProjectileType.Light,
        fireRate: 2,
        shootProbability: 0.002,
        emitProbability: 0.015,
        bonusTypes: [GameBonusType.Health_Increase_5_Shield_60sec],
    },
    [InvaderType.Medium]: {
        type: InvaderType.Medium,
        width: 40,
        height: 40,
        moveSpeed: 80,
        score: 30,
        hp: 4,
        shield: 0,
        damage: 2,
        regenerationRate: 0.3,
        projectileType: ProjectileType.Basic,
        fireRate: 4,
        shootProbability: 0.0035,
        emitProbability: 0.008,
        bonusTypes: [GameBonusType.Weapon_Increase_2_FireRate_60sec],
    },
    [InvaderType.Strong]: {
        type: InvaderType.Strong,
        width: 60,
        height: 60,
        moveSpeed: 40,
        score: 40,
        hp: 5,
        shield: 1,
        damage: 3,
        regenerationRate: 0.3,
        projectileType: ProjectileType.Medium,
        fireRate: 4,
        shootProbability: 0.0001,
        emitProbability: 0.02,
        bonusTypes: [GameBonusType.Health_Increase_5_Shield_60sec],
    },
    [InvaderType.Advanced]: {
        type: InvaderType.Advanced,
        width: 50,
        height: 50,
        moveSpeed: 60,
        score: 30,
        hp: 3,
        shield: 1,
        damage: 2,
        regenerationRate: 0.2,
        projectileType: ProjectileType.Advanced,
        fireRate: 3,
        shootProbability: 0.0004,
        emitProbability: 0.005,
        bonusTypes: [GameBonusType.Weapon_Double_FireRate_30sec, GameBonusType.Experience_Double_Score_60sec],
    },
    [InvaderType.Heavy]: {
        type: InvaderType.Heavy,
        width: 60,
        height: 60,
        moveSpeed: 30,
        score: 40,
        hp: 10,
        shield: 1,
        damage: 5,
        regenerationRate: 0.2,
        projectileType: ProjectileType.Advanced,
        fireRate: 3,
        shootProbability: 0.0001,
        emitProbability: 0.1,
        bonusTypes: [GameBonusType.Health_Increase_5_Shield_60sec],
    },
    [InvaderType.Elite]: {
        type: InvaderType.Elite,
        width: 55,
        height: 55,
        moveSpeed: 30,
        score: 50,
        hp: 7,
        shield: 2,
        damage: 4,
        regenerationRate: 0.4,
        projectileType: ProjectileType.Heavy,
        fireRate: 5,
        shootProbability: 0.0005,
        emitProbability: 0.05,
        bonusTypes: [GameBonusType.Weapon_Double_FireRate_30sec, GameBonusType.Experience_Double_Score_60sec],
    },
    [InvaderType.Boss]: {
        type: InvaderType.Boss,
        width: 80,
        height: 80,
        moveSpeed: 20,
        score: 100,
        hp: 10,
        shield: 3,
        damage: 5,
        regenerationRate: 0.5,
        projectileType: ProjectileType.Ultimate,
        fireRate: 6,
        shootProbability: 0.002,
        emitProbability: 1,
        bonusTypes: [GameBonusType.Health_Double_Shield_30sec, GameBonusType.Weapon_Double_FireRate_30sec, GameBonusType.Experience_Increase_1_Level],
    },
};
