export enum GameBonusType {
    Health_Double_Shield_30sec = "Health_Double_Shield_30sec",
    Health_Increase_1_Shield_60sec = "Health_Increase_1_Shield_60sec",
    Health_Increase_2_Shield_60sec = "Health_Increase_2_Shield_60sec",
    Health_Increase_5_Shield_60sec = "Health_Increase_5_Shield_60sec",
    Weapon_Double_FireRate_5sec = "Weapon_Double_FireRate_5sec",
    Weapon_Double_Firerate_10sec = "Weapon_Double_Firerate_10sec",
    Weapon_Double_Firerate_20sec = "Weapon_Double_Firerate_20sec",
    Weapon_Double_Firerate_30sec = "Weapon_Double_Firerate_30sec",
    Weapon_Increase_05_FireRate_60sec = "Weapon_Increase_05_FireRate_60sec",
    Weapon_Increase_1_FireRate_60sec = "Weapon_Increase_1_FireRate_60sec",
    Weapon_Increase_15_FireRate_60sec = "Weapon_Increase_15_FireRate_60sec",
    Speed_Double_Speed_30sec = "Speed_Double_Speed_30sec",
    Speed_Tripple_Speed_30sec = "Speed_Tripple_Speed_30sec",
    Speed_Increase_5_Speed_60sec = "Speed_Increase_5_Speed__60sec",
    Speed_Increase_10_Speed_60sec = "Speed_Increase_10_Speed__60sec",
    Speed_Increase_20_Speed_60sec = "Speed_Increase_20_Speed__60sec",
    Experience_Increase_500_Score = "Experience_Increase_500_Score",
    Experience_Increase_1000_Score = "Experience_Increase_1000_Score",
    Experience_Increase_1_Level = "Experience_Increase_1_Level",
    Experience_Double_Score_60sec = "Experience_Double_Score_60sec",
}